spring.application.name=find-backend

spring.datasource.url=jdbc:postgresql://localhost:5435/find_db
spring.datasource.username=find_user
spring.datasource.password=find_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=FindBenchSecretKey2026ForUniversityProjectMinimum32Chars
app.jwt.expiration-ms=86400000

server.port=8081

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
